spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rbox
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rbox
    password: dlagywns123!@#
  sql:
    init:
      mode: never
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
