spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rbox
    password: dlagywns123!@#
  sql:
    init:
      mode: never
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml